SUSPICIOUS_TERMS = [
    "verify",
    "password",
    "account",
    "suspended",
    "urgent",
    "immediately",
    "click",
    "login",
    "security alert",
    "confirm",
    "limited time",
    "prize",
    "winner",
    "bank",
    "payment",
    "invoice",
    "wire transfer",
    "gift card",
    "reset",
    "unusual activity",
    "update your information",
    "act now",
    "locked",
    "credentials",
    "social security",
    "refund",
    "attachment",
]

